const studierichtingen = [
	{
		id: 209,
		naam_richting: "Afwerking bouw",
		afbeelding: "",
		beschrijving_richting:
			"De studierichting Afwerking bouw is zowel praktisch als technisch, met een focus op de afwerking van bouwprojecten, inclusief werken in bewoonde gebouwen. Je leert de technieken van de dekvloerlegger, de stukadoor en de vloerder-tegelzetter. Concreet omvat dit het kennen en gebruiken van gereedschappen en materialen voor het afwerken van bouwwerken; het leggen van dek- en gietvloeren, inclusief het mooi uitvoeren en herstellen van naden; en het plaatsen van tegels op vloeren, muren, trappen en terrassen in een mortelbed, gelijmd of in een verse dekvloer, gevolgd door het voegen van de betegelde oppervlaktes (zowel binnen als buiten). Daarnaast leer je droge en natte binnenbepleistering en buitenbepleistering voorbereiden, aanbrengen en beschermen, evenals het plaatsen van gipsblokken. Ook het aanbrengen van lijst- en sierwerk op afgepleisterde vlakken en het voorbereiden, plaatsen en afwerken van droogbouwsystemen komen aan bod. Je leert hoe je IT kunt gebruiken bij het opstellen van een eigen dossier voor de afwerking van een bouwproject. Al dit werk voer je op een veilige manier uit, met aandacht voor herbruikbare grondstoffen en rekening houdend met de EPB*-regelgeving. Tot slot ontwikkel je vaardigheden zoals teamwerk, duidelijke communicatie, werken in verschillende omgevingstemperaturen en het aanpassen aan wijzigingen in planning en omgeving. EPB staat voor ‘EnergiePrestatie en Binnenklimaat’ en heeft betrekking op bepaalde energienormen van je woning, zoals isolatie en luchtdichtheid.",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: ["Realistisch"],
		stroom: null
	},
	{
		id: 210,
		naam_richting: "Binnen- en buitenschrijnwerk",
		afbeelding: "",
		beschrijving_richting:
			"De studierichting Binnen- en buitenschrijnwerk is zowel praktisch als technisch. Je leert hier de competenties van de beroepskwalificaties binnenschrijnwerker en buitenschrijnwerker hout. De focus ligt op het bewerken van massief hout en plaatmaterialen voor schrijnwerk. Je maakt kennis met verspaningstechnologie, wat inhoudt dat je leert hoe je hout bewerkt met technieken zoals boren, draaien en frezen, om zo constructies te maken. Na deze studie kun je binnendeuren, lambrizeringen, plafonds en ander binnenschrijnwerk plaatsen, maar ook ramen, deuren, poorten en gevelbekledingen. Je leert (eigen) ontwerpen maken, onderdelen bewerken, monteren en aansluiten. Het werken met zowel klassieke als computergestuurde machines, en het ontwerpen met ICT en specifieke software, zijn essentieel. Er is ruime aandacht voor herbruikbare grondstoffen, de basiskennis van BIM (digitaal samenwerken), en voor veiligheid en milieu (EPB-regelgeving).",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: ["Realistisch"],
		stroom: null
	},
	{
		id: 211,
		naam_richting: "Binnenschrijnwerk en interieur",
		afbeelding: "",
		beschrijving_richting:
			"Je leert alles wat een binnenschrijnwerker en een interieurbouwer moeten kennen en kunnen, passend bij de beroepskwalificaties. Dit omvat het werken met machines voor houtbewerking, het maken, monteren en aansluiten van onderdelen voor binnenschrijnwerk aan elkaar of aan de ruwbouw, en het plaatsen van binnendeuren, om- en afkastingen, lambrizeringen, plafonds en muren. Je leert je werk voorbereiden in de werkplaats en uitvoeren op de bouwplaats of in reeds bewoonde gebouwen. Professionele communicatie en teamwerk zijn hierbij essentieel. Verder leer je sanitaire en elektrische toestellen integreren in bijvoorbeeld keukens en badkamers, en interieurelementen of meubilair maken en plaatsen voor woningen, kantoren en winkelomgevingen.",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 212,
		naam_richting: "Binnenvaart en beperkte kustvaart",
		afbeelding: "",
		beschrijving_richting:
			"Deze studierichting is erop gericht je op te leiden tot (binnen)schipper en bouwt verder op de kennis die je in de tweede graad al hebt opgedaan. Je verdiept je kennis van mechanica, elektriciteit, motoren en specifieke scheepstechnieken. De theorie wordt uitgebreid ondersteund door diverse praktijkoefeningen, waardoor je de competenties behaalt voor de beroepskwalificatie matroos binnenscheepvaart. Het doel is dat je de schipper leert ondersteunen en zijn opdrachten correct uitvoert. Tijdens stages op binnenwateren en aan de kust, zowel in België als in het buitenland, krijg je ruime gelegenheid om manoeuvres te oefenen op drukke verkeersaders, het schip en de motoren te onderhouden, en op kompas te varen. Je oefent blindvaren op de radar in alle weersomstandigheden, leert de West-Europese vaarwateren grondig kennen en raakt vertrouwd met de binnenlandse sluizen. Verder leer je specifieke vaardigheden zoals aan- en afmeren, schepen koppelen, surveilleren, sturen in geval van nood, helpen bij laden en lossen, passagiersvervoer, eenvoudige herstellingen aan scheepsmotoren en -uitrusting, en huishoudelijke taken aan boord.",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 213,
		naam_richting: "Bouwplaatsmachinist",
		afbeelding: "",
		beschrijving_richting:
			"Wil je graag met grote, sterke en zware machines leren werken? Droom je ervan om graafwerken of hijsopdrachten uit te voeren en materialen zoals aarde, rotsen, zand of bouwelementen te verplaatsen op bouwplaatsen? Dan is de studierichting Bouwplaatsmachinist wellicht iets voor jou. Deze opleiding is zowel praktisch als technisch. Je leert vier types bouwmachines grondig kennen: graafmachines, wielladers, bulldozers en dumpers. Je leert de boordcomputer gebruiken en specifieke taken uitvoeren zoals sleuven graven, graafwerken voor rioleringen, en sloop- en afbraakwerken. Je wordt bekwaam in het besturen, bedienen, onderhouden en controleren van de machines. De opleiding omvat ook het werken met digitale technologieën voor technische voorbereiding en het opstellen van dossiers. Je leert hoe je een veiligheidsfunctie kunt uitoefenen bij bouwprojecten en hoe belangrijk goed overleg en teamwork met de bouwplaatsleiding zijn voor een veilige uitvoering van je job. Dit alles gebeurt steeds met aandacht voor het milieu, veiligheid en het gebruik van zoveel mogelijk herbruikbare grondstoffen, waardoor je alle competenties van de beroepskwalificatie bouwplaatsmachinist verwerft.",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 214,
		naam_richting: "Brom- en motorfietsinstallaties",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 215,
		naam_richting: "Datacommunicatie en netwerkinstallaties",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 216,
		naam_richting: "Decoratie en schilderwerken",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 217,
		naam_richting: "Elektrische installaties",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 218,
		naam_richting: "Fietsinstallaties",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 219,
		naam_richting: "Koelinstallaties",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 220,
		naam_richting: "Koetswerk",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 221,
		naam_richting: "Lassen-constructie",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 222,
		naam_richting: "Mechanische vormgeving",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 223,
		naam_richting: "Onderhoudsmechanica auto",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 224,
		naam_richting: "Podiuminstallaties",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 225,
		naam_richting: "Preventief onderhoud machines en installaties",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 226,
		naam_richting: "Printmedia",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 227,
		naam_richting: "Productie-industrie",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 228,
		naam_richting: "Ruwbouw",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 229,
		naam_richting: "Sanitaire en verwarmingsinstallaties",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 230,
		naam_richting: "Textiel",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 231,
		naam_richting: "Vrachtwagenchauffeur",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 232,
		naam_richting: "Zeevaart",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	},
	{
		id: 233,
		naam_richting: "Zeevisserij",
		afbeelding: "",
		beschrijving_richting: "",
		graad: 3,
		jaren: [5, 6],
		studiedomein: "STEM",
		finaliteit: "Arbeidsmarkt",
		persoonlijkheidstype: [],
		stroom: null
	}
];

export default studierichtingen;
